SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
AND DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC