SELECT
    DISTINCT CC.CAR_ID,
    CC.CAR_TYPE,
    ROUND(30 * CC.DAILY_FEE * (100 - DP.DISCOUNT_RATE) / 100) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS CC
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
    ON
        CC.CAR_ID = RH.CAR_ID
    AND
        START_DATE <= "2022-11-30"
    AND
        END_DATE >= "2022-11-01"
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON
        CC.CAR_TYPE = DP.CAR_TYPE
    AND
        DURATION_TYPE = "30일 이상" 
WHERE
    CC.CAR_TYPE IN ("세단", "SUV")
    AND RH.HISTORY_ID IS NULL
    AND 500000 <= ROUND(30 * CC.DAILY_FEE * (100 - DP.DISCOUNT_RATE) / 100)
    AND ROUND(30 * CC.DAILY_FEE * (100 - DP.DISCOUNT_RATE) / 100) < 2000000
ORDER BY
    FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC