WITH TWENTY_ONE_JOIN_USER AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021')

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT TOJU.USER_ID) AS 'PURCHASE_USERS',
    ROUND(COUNT(DISTINCT TOJU.USER_ID) / (SELECT COUNT(*) FROM TWENTY_ONE_JOIN_USER), 1) AS 'PURCHASE_RATIO'
FROM TWENTY_ONE_JOIN_USER AS TOJU
JOIN ONLINE_SALE AS OS
ON OS.USER_ID = TOJU.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH