SELECT RH.HISTORY_ID, ROUND(RH.DAILY_FEE * (1 - COALESCE(DISCOUNT_RATE * 0.01, 0)) * RH.DURATION, 0) AS FEE
FROM (
    SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
            ELSE "할인 없음"
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CAR
    ON RH.CAR_ID = CAR.CAR_ID
    WHERE CAR_TYPE = "트럭"
    ) AS RH
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON RH.DURATION_TYPE = DP.DURATION_TYPE
AND RH.CAR_TYPE = DP.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC