SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, DOCTOR.MCDP_CD, DOCTOR.DR_NAME, APPOINTMENT.APNT_YMD
FROM APPOINTMENT
JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = ("2022-04-13")
AND APPOINTMENT.MCDP_CD = "CS"
AND APNT_CNCL_YN = "N"
ORDER BY APNT_YMD