SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD BOARD, USED_GOODS_USER USER
WHERE BOARD.WRITER_ID = USER.USER_ID
AND STATUS = 'DONE'
GROUP BY USER.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_PRICE