SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO
WHERE ITEM_INFO.ITEM_ID IN (
SELECT TREE.ITEM_ID
FROM ITEM_INFO AS INFO
JOIN ITEM_TREE AS TREE
ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
WHERE INFO.RARITY = 'RARE')
ORDER BY ITEM_INFO.ITEM_ID DESC