SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS P ON P.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS C ON C.ITEM_ID = T.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC