SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
JOIN SKILLCODES
ON (SKILLCODES.NAME = 'Python' AND (SKILL_CODE & CODE = CODE)) OR (SKILLCODES.NAME = 'C#' AND (SKILL_CODE & CODE = CODE))
ORDER BY ID