SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
ON CAR.CAR_ID = RH.CAR_ID
WHERE CAR_TYPE = "세단"
AND MONTH(START_DATE) = 10
ORDER BY CAR.CAR_ID DESC