SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT 
        ID,
        FISH_TYPE,
        LENGTH,
        ROW_NUMBER() OVER (
            PARTITION BY FISH_TYPE
            ORDER BY LENGTH DESC
        ) AS RN
    FROM FISH_INFO
) T
LEFT JOIN FISH_NAME_INFO
ON T.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE T.RN = 1
ORDER BY T.ID