SELECT CONCAT("/home/grep/src/", FILE.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE
WHERE FILE.BOARD_ID = (
    SELECT BOARD.BOARD_ID
    FROM USED_GOODS_BOARD AS BOARD
    ORDER BY VIEWS DESC
    LIMIT 1)
ORDER BY FILE_ID DESC